# Generated by Django 4.2 on 2023-04-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='passe',
            new_name='paass',
        ),
    ]
